# build environment
FROM node:9
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY app/package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-script@1.1.1 -g --silent
COPY app /usr/src/app
RUN npm run build

# production environment
# Set up NGINX to serve
FROM nginx:1.13.9-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
